# Generated by Django 2.2.13 on 2020-08-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv_item',
            name='description',
            field=models.TextField(default='backlog text'),
            preserve_default=False,
        ),
    ]
