# Generated by Django 2.2.13 on 2020-08-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_cv_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv_category',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cv_item',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
